### ISSUE TITLE
No estimate on local webpages?

### ISSUE THREAD

**Issue by olivertwistor** [danielrozenberg/how-long-to-read#139]
I really like your plugin. However, I've encountered a problem I haven't been able to solve. It seems that there is no estimate on webpages local on my machine. They contain only valid HTML (including enclosing html and body tags, so I don't understand why it wouldn't work on local files. 

When I try the same files in my local webserver, the plugin works. Is there some setting in Firefox I have to toggle to enable plugins to work with local files?

I'm aware that the plugin doesn't show an estimate if the estimate is shorter than 1 minute, but I've tested on a locally downloaded book from Project Gutenberg.

**Comment by danielrozenberg** [comment]
Looks like I just misconfigured the extension and set it to only work on HTTP/HTTPS, and not on local files. Fixed this in f362310, try updating to v1.0.5 (Firefox usually updates extensions automatically, but it might take some time, so try updating it manually from your about:addons page).

I'm closing this issue as fixed, feel free to reopen if this still doesn't work for you!
