### ISSUE TITLE
Change words per minute?

### ISSUE THREAD

**Issue by coldnrainy** [danielrozenberg/how-long-to-read#61]
This is a great, much-needed extension, so first, thank you. Would it be possible to add an option to change the reading speed? Or perhaps to at least know where it is set? I have another extension, [Reading Time](https://addons.mozilla.org/en-US/firefox/addon/reading-time/), which hasn't been updated in years, and the times differ between it and yours. Reading Time uses 200 wpm. Thanks again.

**Comment by danielrozenberg** [comment]
I've been thinking about making this a setting in the extension but didn't know if anyone cares enough! (this extension has 15 users... not exactly a crowd)

I don't get a lot of time to work on my side projects but I can take a stab at it in the next few weeks :) I'll set a reminder so this won't fall between the cracks

**Comment by coldnrainy** [comment]
That is shocking to me. It is a much needed extension. The only other one
serving this function is Reading Time which creates an overlay in the right
lower corner of the screen. Much more obtrusive. Thanks for your time on
this!

**Comment by danielrozenberg** [comment]
This should be fixed in version 1.0.3 which I have just uploaded to Mozilla!
