### ISSUE TITLE
Inaccurate estimate - with overlay

### ISSUE THREAD

**Issue by coldnrainy** [danielrozenberg/how-long-to-read#63]
On this page: https://www.theatlantic.com/business/archive/2018/01/german-board-games-catan/550826/

It is giving me 1 min for ~276 words. I suspect that it is calculating based on the overlay perhaps?

**Comment by danielrozenberg** [comment]
Yeah, unfortunately not all website work perfectly. It's on my plate to fix it, but the module I'm using to [extract the main text](extract-main-text) hasn't been maintained in a long time. I should collect a listing of websites where this extension doesn't give a good estimate and see how I can generalize this

**Comment by coldnrainy** [comment]
This one works pretty well with text extraction but it has a very obtrusive
popup that returns every time you navigate to a new page. Also you can't
change the reading speed. You could fork this one or perhaps use its text
extraction mechanism. https://github.com/scripts-richard/reading_time

**Comment by danielrozenberg** [comment]
This should be fixed for most pages now, and if the estimate is blocked by a popup and you want to re-run it after you dismiss the popup just click on the button :)

I'm closing it for now, reopen this issue if you find more cases where the estimate is way off!

**Comment by coldnrainy** [comment]
Thank you so much! It is greatly improved!

One issue I noticed is it doesn't seem to differentiate between article
text and comments and various links. For example:
https://www.nejm.org/doi/full/10.1056/NEJMp2006372?query=TOC

This give me a reading time of 18 minutes but the article is only 1228
words, so it should be around 6-7 minutes for average reading time.

**Comment by danielrozenberg** [comment]
Yep, it's the compromise I had to make. There's no one perfect way to find what is the main text of a web page. At first I used an external package, but it was kinda flaky in its results. I switched to just grabbing all the visible text on the page (so things hidden inside navigation menus won't be counted, for example) but that means it counts the comments as well...
